[tools]
node = "24"
usage = "latest"
go = "latest"
python = "3.14"
"npm:prettier" = "latest"
"npm:@qwen-code/qwen-code" = "latest"
"npm:pyright" = "latest"
"npm:opencode-ai" = "latest"
"npm:npm-check-updates" = "latest"
ruby = "latest"
rust = "latest"
"npm:pnpm" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
env_shell_expand = true
