[tools]
node = "22"
usage = "latest"
go = "latest"
python = "3.13"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:prettier" = "latest"
"npm:@qwen-code/qwen-code" = "latest"
"npm:pyright" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
