[tools]
node = "20"
usage = "latest"
go = "latest"
python = "3.13"
uv = "latest"
"pipx:git+https://github.com/negineri/moro.git" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
